### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#107]
# Roadmap

This issue will serve as a roadmap outlining the major features planned for the first release candidate of Stump, `v0.1.0`, as well as some notes regarding potential post-release goals. This should be treated as a mostly static document, as the features listed are what I consider to be the minimum set to reach a viable release. The section dedicated to post-release features may receive more updates, though. Also note that a few features listed will be more-so *nice to haves*, rather than hard requirements.

## Pre-Release Items

Below are all of the essential features that will need to be completed with at least minimal functionality before the first `v0.1.0` release candidate is slated:

- [ ]  Miscellaneous maintenance and code smell cleaning
    - [ ]  Reorganize and consolidate some of the `client` code, its *very* messy
        - [x]  Split `api` into separate package to house all the axios functions
        - [x]  Rework gross hooks + callback types
            - [x] Fix base query hooks, e.g. custom `useQuery`
            - [x] Use corrected base queries for all existing hooks
    - [x]  Revert the whole `prelude` crate, organize in other crates where it makes sense
    - [ ]  Audit dependencies, prune where needed
    - [ ]  Fix all the peer dependency warnings (where needed, F you storybook lol)
    - [ ]  `cargo report future-incompatibilities --id 4 --package rustc-serialize@0.3.24`
    - [ ]  `local-ip-address` check if release yoinked comes back okay
    - [x]  Optimize [[moonrepo](https://moonrepo.dev/docs)](https://moonrepo.dev/docs) setup
    - [ ]  Tighten logging noise in `core`
    - [ ]  Revisit rework of `StumpConfig` for more efficient environment parsing
- [ ]  General `server` upgrades
    - [x]  Migrate to Axum v0.6
    - [x]  Look into sqlite session store at some point to replace the in memory store.
    - [x]  Consider refactoring queries to use more current select/include patterns
        - [https://prisma.brendonovich.dev/reading-data/select-include#many-relation-options](https://prisma.brendonovich.dev/reading-data/select-include#many-relation-options)
    - [x]  Change HTTP endpoints to be **unpaged** by default (except opds)
- [ ]  Add proper testing
    - This will not hold up a release, it is a fairly large and complicated undertaking. I feel that initially, while not *ideal*, it would be OK to release without this. Then, to to help ensure general code safety, testing should be prioritized alongside new features and bug fixes.
    - [ ]  Rework `integration_tests`
    - [ ]  Add unit testing throughout `core`
    - [ ]  Add unit testing throughout `server`
    - [ ]  Consider testing UI elements
- [x]  Refine Stump color palette (gray colors are :barf:)
- [x]  Start building out, but don't use quite yet, custom UI components in new package `components`
    - [x]  [https://github.com/shadcn/ui](https://github.com/shadcn/ui)
- [ ]  Rewrite job system
    - Note that these are super complicated with Rust, and they all might not fit into the first release. At a minimum, jobs will be cancellable.
    - [ ]  Introduce more stateful-ness with job variants
    - [x]  Support cancelling jobs
    - [ ]  Support pausing jobs
    - [ ]  Save job queue / active workers state during a graceful shutdown
    - [ ]  Restore job queue / active workers state after graceful shutdown
- [ ]  Complete major UI scenes to at least MVP stage:
    - [x]  `HomeScene`
        - [x]  Continue Reading, Recently Added, Etc.
        - [x]  Statistics
            - Note: I'd like more, but I think this is enough for MVP
        - [x]  `TopBar`
            - Currently unsure what should go here
    - [ ]  book/epub
        - [x]  `BookOverviewScene`
            - [x]  Show progress (if any)
            - [x]  Show next in series (using a new `cursor` page param?)
            - [x]  Render book description
                - [x]  Plain text
                - [x]  Support markdown
            - [x]  File information and tags
        - [ ]  readers:
            - [ ]  `ImageBasedReader`
                - [x]  ToolBar
                    - [x]  Fix overly eager image loading
                - [ ]  Support two-page layout
                    - This may be post-release
            - [ ]  `AnimatedImageBasedReader`
                - This will not hold up a release, as it is mostly “extra” functionality on top of non-animated variant
                - [ ]  Correctly implement desired page swipe animation.
            - [ ]  `EpubLazyReader`
                - [x]  syncs `epubcfi` and `progress_percentage` tracking updates with server as reading
                - [x] Restores progress accordingly in UI (i.e. go to correct page based on `epubcfi`)
                - [ ] https://github.com/aaronleopold/stump/issues/114
    - [x]  series
        - [x]  `SeriesOverviewScene`
            - [x]  Add series information on 0th page
            - [x]  Support filtering and ordering of grids/lists 
    - [ ]  library
        - [x] `LibraryOverviewScene`
            - [x]  Add library information on 0th page
            - [x]  Support filtering and ordering of grids/lists
        - [x]  `LibraryExplorerScene`
            - This will **not** hold up a release
            - [x]  Support basic filesystem navigation
            - [x]  Double-clicking media should route to appropriate scene
        - [ ]  `CreateLibraryScene`
            - [x]  Replaces all functionalities from the previous modal implementation
            - [x]  Support configuring scanner options
            - [ ]  Tag management
        - [ ]  `UpdateLibraryScene`
            - [x]  Replaces all functionalities from the previous modal implementation
            - [x]  Support updating scanner options
            - [ ]  Tag management
    - [ ]  settings
        - [x]  `GeneralSettingsScene`
            - [x]  Users can update their username and password
            - [x]  Users can update their locale preferences
            - [x]  Users can update their avatar image URL
            - [x]   Probably one or two more things (this page is rather bland ATM)
        - [ ]  `UserManagementScene`
            - [x]  Admins can create users
            - [x]  Admins can delete users
                - [x]  soft delete
                - [x]  hard delete
            - [x]  Admins can view users
            - [ ]  Admins can update *certain* user attributes
                - [ ]  e.g. remove offensive or otherwise unwanted avatars
         - [x] `JobsAndConfigurationScene`
             - [x] TODO 
         - [ ]  `SeverConfigurationScene`
             - [ ] TODO 
    - [x] Remove all those `Loading...` placeholders 🤢
- [x]  Store redirects for unauthenticated access via HTTP calls
        - I.e. if I visit `/some-page/1`, and get redirected to `/auth`, should redirect instead with query params to restore state: `/auth?redirect=/some-page/1`
    - [x]  All client side routing and API calls
    - [x]  Swagger UI
- [ ]  Scanner
    - [ ]  Create new option for series dedicated scan
    - [ ]  More content-aware scan resolutions
        - This is *very* complex, and might be pushed to post-release.
        - [ ]  Support restoring missing library if newly scanned library “matches” missing one
        - [ ]  Support restoring missing series if newly scanned series “matches” missing one
            - Note that there is a VERY naive implementation of these, but it simply won't cut it. So I am not counting them as done.
    - [x]  Restrict concurrency to avoid performance degradation
    - [ ]  Configuration
        - [x]  Per-library basis
        - [ ]  Support `.stumpignore` files to alter what the scanner will look at
        - [x]  Support generating thumbnails https://github.com/aaronleopold/stump/issues/44
            - [x]  Generic, downscaled `webp` generation
            - [x]  Specific, user-configured, scaling options:
                - [x]  Custom scaled height and width (e.g. `0.5 x 0.75`)
                - [x]  Custom scaled (e.g. `0.5`, equal to `0.5 x 0.5` above)
                - [x]  Custom size in pixels (e.g. `331.5 x 512`)
            - [x]  Specific, user-configured, output formats:
                - [x]  `png`
                - [x]  `jpg`
                - [x]  `webp`
- [ ] Minimal RBAC / ABAC https://github.com/aaronleopold/stump/issues/41
- [ ] Basic reading list support https://github.com/aaronleopold/stump/issues/37
    - At the very least, I'd like to be able to have users create a reading list and edit/delete them.
- [x] Format support
    - Each format should generally support the following:
        - Basic metadata collection (pages, file size, generation of checksum hash, etc)
        - Page extraction (excluding EPUB until https://github.com/aaronleopold/stump/issues/62)
        - Thumbnail extraction
        - Progress tracking while reading with Stump readers
    - [x]  ZIP
        - Maybe support https://github.com/iComics/comicbookinfo for pre-release.
    - [x]  PDF
        - This may be a post-release item (I hate PDF)
    - [x]  RAR
        - **Currently excluding Docker, as there is a nasty bug that renders RAR unsupported in Docker**
        - [x]  Support RAR-to-ZIP converting
        - [x]  If `0.5` unrar release lands:
            - [https://github.com/muja/unrar.rs/issues/26](https://github.com/muja/unrar.rs/issues/26)
            - [x]  Move off of custom `read_bytes` implementation
            - [x]  Try and resolve [https://github.com/aaronleopold/stump/issues/38](https://github.com/aaronleopold/stump/issues/38)!
    - [x]  EPUB
        - [x]  `epubcfi` and `progress_percentage` for progress tracking
        - [x] Generate TOC from meta
- [ ]  Finish CI workflows https://github.com/aaronleopold/stump/issues/93
    - [x]  Setup self hosted runner
- [ ]  Add some automated system for versioning/releases
- [ ]  Documentation
    - [ ]  Finish writing it lol
    - [ ]  Ensure all configuration options are documented
- [ ]  Thorough user testing!!
    - [ ]  I’d like a solid 2-week period of at least a handful of testers using Stump trying to break it wherever possible

## Post-Release Items

First and foremost, the top priority after the initial release will be bug fixes and maintenance. If you've read the entire `Pre-Release Items` section, you'll know that `v0.1.0` is intended to be a sort of MVP, and not a fully featured option *yet*. That being said, the following are things I'd like to explore afterwards, also not necessarily in priority order:

- [ ]  Desktop App
    - Note: this should be very little effort, and will only really require:
        - [ ]  GitHub actions to run the builds/uploads
        - [ ]  Discord presence would be cool https://github.com/aaronleopold/stump/issues/60
- [ ]  Tachiyomi Support https://github.com/aaronleopold/stump/issues/48
    - [ ]  While one day I would like to create an in-house mobile application, since I can re-use some of the code for web/desktop, priority will be here
- [ ]  Look into better validation for some HTTP inputs via [https://github.com/Keats/validator](https://github.com/Keats/validator)
- [x]  Rethink HTTP endpoints allow better range of filter options
    - [x]  Basic structure implemented, just a matter of prioritizing it time permitting
- [x]  Consider paying for small hosted Stump instance for demo purposes
    - [x]  Support a sort of demo mode with restricted functionalities
- [ ]  Start work towards `benchmarks` crate

**Comment by aaronleopold** [comment]
Closing this as to not maintain multiple lists. I'll just be using [projects](https://github.com/stumpapp/stump/projects?query=is%3Aopen)
