### ISSUE TITLE
0.1.0 Mobile App Roadmap

### ISSUE THREAD

**Issue by dancamdev** [stumpapp/stump#125]
## Roadmap 🗺️

With the `v0.1.0` release of the Stump server (very) slowly approaching, the mobile app has the following items targeted for an _initial POC_:

- [ ] Various initial expo-related project configuration:
  - [x] #128
  - [x] #126
- [x] Configure and connect to a Stump server instance
- [x] Login or claim an unclaimed server instance
- [ ] A home screen that shows the server at a glance:
  - [x] Various server statistics
  - [ ] In progress media
  - [ ] Newly added series and books
- [ ] A library screen that shows a paginated list of series within a library
- [ ] A series screen that shows a pagination list of media within a series
- [ ] A very basic book overview screen
- [ ] Support barebones readers for:
  - [ ] Epub
  - [ ] CBZ/CBR
- [ ] Dark theme support

Progress detailed here has been done on the `mobile-app` branch of the project, so if you want to lend a hand, make sure you fork that!

**Comment by aaronleopold** [comment]
A little note for future me, the `i18n` folder in the `interface` package will eventually need to be moved outside to a separate package to the mobile app can properly consume it.

**Comment by aaronleopold** [comment]
Closing in favor of a dedicated project: https://github.com/orgs/stumpapp/projects/8/views/1
