### ISSUE TITLE
[FEATURE] Time-based statistics meta for books

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#341]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to configure the following:

- Average page-read time for image-based books
- Average WPM for other books (i.e. ebooks)

In order to compute an estimated time to read / time left until finished statistic.

**Describe the solution you'd like**

- [ ] Introduce a new analysis task for counting the words in an EPUB file
- [ ] Implement basic function for estimating remaining word count based on current place in epub
    - This can be a rough estimate based on the percentage, or more accurate if counting from the current epubcfi string 
- [ ] Implement basic time estimate functions for:
    - [ ] Time to read X words based on Y/min configured rate
    - [ ] Time to read X image-based pages based on Y/min configured rate

I'd love to then someday support showing people things like:

- You've read X words
    - Estimated WPM based on start/end times of finished books and corresponding word counts
- You've read X pages
